
services:

  # backend:
  #   image: employee_management_backend:0.01
  #   container_name: em_backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MYSQL_HOST=mysql  
  #   depends_on:
  #     - mysql

    # client:
  #   image: employee_management_client:0.01
  #   container_name: em_client
  #   ports:
  #     - "3000:80"


  authentication:
    image: employee_management_authentication:0.02
    container_name: em_authentication
    ports:
      - "443:443"
    environment:
      - JWT_ACCESS_TOKEN_SECRET=iAmLordVoldemort
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=1h
      - JWT_REFRESH_TOKEN_SECRET=tomRiddle
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=1d
      - DATABASE_URL=mysql://user:secret@authentication_sql:3306/authentication
    depends_on:
      authentication_sql:
        condition: service_healthy

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   command: --init-file /data/application/init.sql
  #   volumes:
  #     - ./init.sql:/data/application/init.sql
  #     - my-datavolume:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_USER=root
  #     - MYSQL_ROOT_PASSWORD=secret
  #     - MYSQL_DATABASE=deathStar
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_ROOT_HOST=%

  authentication_sql:
    image: mysql:latest
    container_name: authentication_sql
    ports:
      - "3307:3306"
    command: --init-file /data/application/init.auth.sql
    volumes:
      - ../authentication/init.auth.sql:/data/application/init.auth.sql
      - auth-db-data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=authentication
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_HOST=%    
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'authentication_sql', '-u$$MYSQL_ROOT_USER', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 5s
      retries: 10  
volumes:
  my-datavolume:
  auth-db-data-volume:
    external: true
